[package]
name = "quark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
flate2 = "1.0.23"
tar = "0.4.38"
subprocess = "0.2.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"