use super::{Handler, Result};
use clap::Args;

/// Arguments for `RunCommand`
///
/// Usage :
/// `quark run --quardle <QUARDLE> --output <OUTPUT>`
#[derive(Debug, Args)]
pub struct RunCommand {
    /// Location of the quardle
    #[clap(short, long)]
    quardle: String,

    /// Folder containing the files generated by the quarks necessary to work
    #[clap(short, long)]
    output: String,
}

/// Method that will be called when the command is executed.
impl Handler for RunCommand {
    fn handler(&self) -> Result<()> {
        Ok(())
    }
}
